# 欢迎使用 Jekyll！
#
# 此配置文件用于影响整个站点的设置，这些值
# 只需设置一次，之后很少进行编辑。如果您发现自己经常编辑这些文件，请考虑使用 Jekyll 的数据文件
# 功能来获取需要经常更新的数据。
#
# 由于技术原因，当您使用
# 'jekyll serve' 时，此文件不会自动重新加载。如果您更改此文件，请重新启动服务器进程。
# 站点设置
# 这些用于个性化您的新站点。如果您查看 HTML 文件，
# 您将看到它们通过 {{ site.title }}、{{ site.github_repo }} 等访问。
# 您可以创建任何您想要的自定义变量，并且它们将通过 {{ site.myvariable }} 在模板中访问。

title: WendellManual
description: Wendell's Manual
baseurl: "" # 您网站的子路径，例如 /blog
url: "https://wendell.website/WendellManual/" # 您网站的基本主机名和协议，例如 http://example.com
repository: XiaoWendell/WendellManual # 用于 github-metadata


permalink: pretty

defaults:
  - scope:
      path: "docs" # 此处的空字符串表示项目中的所有文件
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # 特定于主题网站: 
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # 主题测试代码
  - fixtures/

# 设置将显示的徽标的路径/URL 而不是标题
#logo: "/assets/images/just-the-docs.png"

# 启用或禁用站点搜索
# 支持 true（默认）或 false
search_enabled: true
search:
  # 将页面拆分为可单独搜索的部分
  # 支持 1 - 6，默认值: 2
  heading_level: 2
  # 每个搜索结果的最大预览数量
  # 默认值: 3
  previews: 2
  # 在预览中匹配单词前显示的最大单词数量
  # 默认值: 5
  preview_words_before: 3
  # 在预览中匹配单词后显示的最大单词数量
  # 默认值: 10
  preview_words_after: 3
  # 设置搜索标记分隔符
  # 默认值: /[\s\-/]+/
  # 示例: 启用对带连字符的搜索词的支持
  tokenizer_separator: /[\s/]+/
  # 在搜索结果中显示相对 URL
  # 支持 true（默认）或 false
  rel_url: true
  # 启用或禁用出现在每个页面右下角的搜索按钮
  # 支持 true 或 false（默认）
  button: false
  # 通过按 `ctrl + focus_shortcut_key`（或 macOS 上的 `cmd + focus_shortcut_key`）
  focus_shortcut_key: “k”

# 代码上的复制按钮
enable_copy_code_button: true

# 默认情况下，将主题作为宝石使用会导致美人鱼被禁用；这是可选的
mermaid:
  # mermaid 库的版本
  # 从 https://cdn.jsdelivr.net/npm/mermaid/ 中选择一个可用版本
  version: "11.4.0"
  # 将任何其他配置（例如设置主题）放入 _includes/mermaid_config.js 中
  # 另请参阅 docs/ui-components/code

  # 要从本地库加载 mermaid，还请使用 `path` 键指定库的位置；例如
  # for (v10+):
  path: "  assets/files/mermaid-11.4.0/package/dist/mermaid.esm.min.mjs"
  # path: “/assets/js/mermaid.esm.min.mjs”
  # for (<v10):
  # path: “/assets/js/mermaid.min.js”
  # 注意: 将 `mermaid.esm.min.mjs`（v10+）或 `mermaid.min.js`（<v10）以及关联的 `.map` 文件从指定版本的 `mermaid/dist` 复制到 `/assets/js/`。

# 启用或禁用标题锚点
heading_anchors: true

# 右上角导航的辅助链接
aux_links:
  "Blog":
    - "https://XiaoWendell.github.io"

# 使辅助链接在新选项卡中打开。默认值为 false
aux_links_new_tab: false

# 全局启用或禁用侧面/移动菜单
# 还可以使用页面变量或最小布局选择性地启用或禁用导航菜单
nav_enabled: true

# 导航链接的排序顺序
# nav_sort: case_insensitive # 默认，相当于 nil
nav_sort: case_sensitive # 大写字母排在小写字母之前

# 外部导航链接
nav_external_links:
  - title: Wendell on GitHub
    url: https://github.com/XiaoWendell

# 显示导航错误报告
nav_error_report: true # 默认值为 false/nil。

liquid:
  error_mode: strict
  strict_filters: true

# 页脚内容
# 出现在每个页面主要内容的底部

# 返回顶部链接
back_to_top: true
back_to_top_text: "返回顶部"

# 页脚内容
footer_content: '版权所有 &copy; 2017-2025 <a href="https://github.com/XiaoWendell">Wendell</a>。由 <a href="https://github.com/XiaoWendell/WendellManual/tree/master/LICENSE.txt">MIT 许可证</a> 分发。本网站由 <a href="https://www.netlify.com/">Netlify</a> 提供支持。'
# 页脚最后编辑时间戳
last_edit_timestamp: true # 显示或隐藏编辑时间 - 页面必须在前言中定义 `last_modified_date`
last_edit_time_format: "%b %e %Y at %I:%M %p" # 使用 ruby​​ 的时间格式: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# 页脚 “在 GitHub 上编辑此页面” 链接文本
gh_edit_link: true # 显示或隐藏编辑此页面链接
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/XiaoWendell/WendellManual" # 你的 repo 的 github URL
gh_edit_branch: "master" # 您的文档所来自的分支
# gh_edit_source: docs # 您的文件来源
gh_edit_view_mode: "edit" # 如果您希望用户立即跳转到编辑器，则使用“tree”或“edit”

# 配色方案目前仅支持 "dark", "light"/nil (default)或您定义的自定义方案
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics 跟踪（可选）
# 支持跟踪 ID 字符串的 CSV（例如“UA-1234567-89,G-1AB234CDE5”）
# 注意: Just the Docs 主站点*不*使用 Google Analytics。
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # 使用符合 GDPR 的 Google Analytics 设置（默认为 true/nil）

# Google Analytics 跟踪（可选）
ga_tracking: G-EFC4LK52FZ
ga_tracking_anonymize_ip: true # 使用符合 GDPR 的 Google Analytics 设置（默认为 true/nil）


plugins: # 插件，用于生成站点
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
