# 欢迎使用 Jekyll！
#
# 此配置文件用于影响整个站点的设置，这些值
# 只需设置一次，之后很少进行编辑。如果您发现自己经常编辑这些文件，请考虑使用 Jekyll 的数据文件
# 功能来获取需要经常更新的数据。
#
# 由于技术原因，当您使用
# 'jekyll serve' 时，此文件不会自动重新加载。如果您更改此文件，请重新启动服务器进程。
# 站点设置
# 这些用于个性化您的新站点。如果您查看 HTML 文件，
# 您将看到它们通过 {{ site.title }}、{{ site.github_repo }} 等访问。
# 您可以创建任何您想要的自定义变量，并且它们将通过 {{ site.myvariable }} 在模板中访问。

title: WendellManual
description: Wendell's Manual
baseurl: "" # 您网站的子路径，例如 /blog
url: "https://wendell.website/WendellManual/" # 您网站的基本主机名和协议，例如 http://example.com
repository: https://github.com/XiaoWendell/WendellManual # 用于 github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # 此处的空字符串表示项目中的所有文件
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # 特定于主题网站: 
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # 主题测试代码
  - fixtures/

# 设置将显示的徽标的路径/URL 而不是标题
#logo: "/assets/images/just-the-docs.png"

# 启用或禁用站点搜索
# 支持 true（默认）或 false
search_enabled: true
search:
  # 将页面拆分为可单独搜索的部分
  # 支持 1 - 6，默认值: 2
  heading_level: 2
  # 每个搜索结果的最大预览数量
  # 默认值: 3
  previews: 2
  # 在预览中匹配单词前显示的最大单词数量
  # 默认值: 5
  preview_words_before: 3
  # 在预览中匹配单词后显示的最大单词数量
  # 默认值: 10
  preview_words_after: 3
  # 设置搜索标记分隔符
  # 默认值: /[\s\-/]+/
  # 示例: 启用对带连字符的搜索词的支持
  tokenizer_separator: /[\s/]+/
  # 在搜索结果中显示相对 URL
  # 支持 true（默认）或 false
  rel_url: true
  # 启用或禁用出现在每个页面右下角的搜索按钮
  # 支持 true 或 false（默认）
  button: false
  # 通过按 `ctrl + focus_shortcut_key`（或 macOS 上的 `cmd + focus_shortcut_key`）
  focus_shortcut_key: “k”

# 代码上的复制按钮
enable_copy_code_button: true

# 默认情况下，将主题作为宝石使用会导致美人鱼被禁用；这是可选的
mermaid:
  # mermaid 库的版本
  # 从 https://cdn.jsdelivr.net/npm/mermaid/ 中选择一个可用版本
  version: "9.1.6"
  # 将任何其他配置（例如设置主题）放入 _includes/mermaid_config.js 中
  # 另请参阅 docs/ui-components/code
  # 要从本地库加载 mermaid，还请使用 `path` 键指定库的位置；例如
  # for (v10+):
  # path：“/assets/js/mermaid.esm.min.mjs”
  # for (<v10):
  # path：“/assets/js/mermaid.min.js”
  # 注意：将 `mermaid.esm.min.mjs`（v10+）或 `mermaid.min.js`（<v10）以及关联的 `.map` 文件从指定版本的 `mermaid/dist` 复制到 `/assets/js/`。

# 启用或禁用标题锚点
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "https://github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs

# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a> <a href="https://www.netlify.com/">This site is powered by Netlify.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
